---
name: Build

permissions:
  "packages": "write"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "wissididom/timestamp-temperature-bot"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into docker registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          file: ./Dockerfile
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}
          cache-to: type=inline

      - name: Push docker image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          file: ./Dockerfile
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}
          cache-to: type=inline
